version: '3'

services:
    twitchdb:
        image: postgres   
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_PASSWORD: SecurePassword1!
            POSTGRES_DB: twitch
        volumes:
            - twitchdbpostgres:/var/lib/postgresql/data
    twitchlogger:
        build:
            context: ./TwitchLogger
        restart: always
    twitchdataapi:
        build:
            context: ./TwitchDataApi
        ports:
            - "3000:3000"
        restart: always

volumes:
    twitchdbpostgres: