version: '3'

services:
    twitchdb:
        image: mongo   
        ports:
            - "27017:27017"
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: rootusername
            MONGO_INITDB_ROOT_PASSWORD: rootpassword
        volumes:
            - twitchdb:/data/db
        command: --auth
    twitchlogger:
        build:
            context: ./TwitchLogger
        restart: always
    twitchdataapi:
        build:
            context: ./TwitchDataApi
        ports:
            - "3000:3000"
        restart: always

volumes:
    twitchdb: